# Form implementation generated from reading ui file 'C:\Users\Torre\Documents\Coding\python\Test\pyqt_privatesingal\ui_combineExcel.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_combineExcel(object):
    def setupUi(self, Dialog_combineExcel):
        Dialog_combineExcel.setObjectName("Dialog_combineExcel")
        Dialog_combineExcel.resize(800, 800)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_combineExcel)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_dirshow = QtWidgets.QLineEdit(Dialog_combineExcel)
        self.lineEdit_dirshow.setObjectName("lineEdit_dirshow")
        self.horizontalLayout.addWidget(self.lineEdit_dirshow)
        self.pushButton_selectdir = QtWidgets.QPushButton(Dialog_combineExcel)
        self.pushButton_selectdir.setObjectName("pushButton_selectdir")
        self.horizontalLayout.addWidget(self.pushButton_selectdir)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.listWidget_filename = QtWidgets.QListWidget(Dialog_combineExcel)
        self.listWidget_filename.setObjectName("listWidget_filename")
        self.verticalLayout.addWidget(self.listWidget_filename)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(Dialog_combineExcel)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.progressBar = QtWidgets.QProgressBar(Dialog_combineExcel)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_2.addWidget(self.progressBar)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.pushButton_remove = QtWidgets.QPushButton(Dialog_combineExcel)
        self.pushButton_remove.setObjectName("pushButton_remove")
        self.verticalLayout.addWidget(self.pushButton_remove)
        self.pushButton_combine = QtWidgets.QPushButton(Dialog_combineExcel)
        self.pushButton_combine.setObjectName("pushButton_combine")
        self.verticalLayout.addWidget(self.pushButton_combine)

        self.retranslateUi(Dialog_combineExcel)
        QtCore.QMetaObject.connectSlotsByName(Dialog_combineExcel)

    def retranslateUi(self, Dialog_combineExcel):
        _translate = QtCore.QCoreApplication.translate
        Dialog_combineExcel.setWindowTitle(_translate("Dialog_combineExcel", "Dialog"))
        self.pushButton_selectdir.setText(_translate("Dialog_combineExcel", "select dir"))
        self.label.setText(_translate("Dialog_combineExcel", "merge progress"))
        self.pushButton_remove.setText(_translate("Dialog_combineExcel", "remove"))
        self.pushButton_combine.setText(_translate("Dialog_combineExcel", "merge"))
